---
title: "Initial Analysis for Few Shot Learning"
output:
  pdf_document:
    latex_engine: xelatex
---

```{r, echo=FALSE}
library(tidyverse)
library(brms)
library(lme4)
library(lmerTest)
library(plotrix)
library(stringr)
library(readxl)
library(RColorBrewer)
library(Hmisc)

options(scipen = 999) 
```


# Verbal Argument Structure



## Stats Tests
```{r}
supervision_test = function(df){
  m1 = glmer(acc ~ model + freq_cat + (1|X), family = binomial, data = df %>% filter(model == "rnng" | model == "lstm") )
  m2 = glmer(acc ~ model + freq_cat + (1|X), family = binomial, data = df %>% filter(model == "actionLstm" | model == "lstm") )
  
  print( summary(glmer(acc ~ model + freq_cat + (1|X), family = binomial, data = df %>% filter(model == "actionLstm" | model == "rnng") )))

  df = df %>%
    summarise(e_rnng = round(coef(summary(m1))[2], 5),
              p_rnng = round(coef(summary(m1))[11], 5),
              e_action = round(coef(summary(m2))[2], 5),
              p_action = round(coef(summary(m2))[11], 5))
}


exposure_test = function(df){
  m = glm(acc ~ freq_cat, family = binomial, data = df)
  df = df %>% summarise( e = coef(summary(m))[2],
                         p = coef(summary(m))[8])
}

fewshot_test = function(df){
  #print(unique(df$test))
  #print(unique(df$freq_cat))
  
  ngram_acc = df %>% filter(model=="ngram") %>% select(acc) %>% as_vector()
  t.ngram = binom.test(sum(ngram_acc), length(ngram_acc), p = 0.5, alternative="greater")$p.value
  lstm_acc = df %>% filter(model=="lstm") %>% select(acc) %>% as_vector()
  t.lstm = binom.test(sum(lstm_acc), length(lstm_acc), p = 0.5, alternative="greater")$p.value
  action_acc = df %>% filter(model=="actionLstm") %>% select(acc) %>% as_vector()
  t.action = binom.test(sum(action_acc), length(action_acc), p = 0.5, alternative="greater")$p.value
  rnng_acc = df %>% filter(model=="rnng") %>% select(acc) %>% as_vector()
  t.rnng = binom.test(sum(rnng_acc), length(rnng_acc), p = 0.5, alternative="greater")$p.value

  #m1 = glm(acc ~ model + (1|freq), family = binomial, data = df %>% filter(model == "lstm" | model == "5gram") )
  #m2 = glm(acc ~ model + (1|freq), family = binomial, data = df %>% filter(model == "actionLstm" | model == "5gram") )
  #m3 = glm(acc ~ model + (1|freq), family = binomial, data = df %>% filter(model == "rnng" | model == "5gram") )

  df = df %>%
    summarise(t.ngram = round(t.ngram, 5), t.lstm = round(t.lstm,5), t.action = round(t.action,5), t.rnng = round(t.rnng,5))
              #e_lstm = round(coef(summary(m1))[2], 5),
              #p_lstm = round(coef(summary(m1))[8], 5),
              #e_action = round(coef(summary(m2))[2], 5),
              #p_action = round(coef(summary(m2))[8], 5),
              #e_rnng = round(coef(summary(m3))[2], 5),
              #p_rnng = round(coef(summary(m3))[8], 5)),
  return(df)
}


```


```{r}
plot_accs = function(df_raw, df_summary, filename, h, w, title){
  df_raw = df_raw %>%
    mutate(model = factor(model, levels = c("ngram", "lstm", "actionLstm", "rnng")))
  df_summary = df_summary %>%
    mutate(model = factor(model, levels = c("ngram", "lstm", "actionLstm", "rnng")))
  
  ggplot() +
    theme_bw()+
    stat_smooth(geom = "line", data = df_raw, aes(x=log10(freq_cat), y=acc, color=model), method = 'glm', method.args = list(family = "binomial"), size = 1, alpha=0.5) +
    stat_smooth(data = df_raw, aes(x=log10(freq_cat), y=acc, color=model), method = 'glm', method.args = list(family = "binomial"), size = 0, alpha=0.2) +
  
    geom_point(data = df_summary, aes(x=freq_cat, y=m, color = model, fill=model), stat="identity", position="dodge", size=2) +
    geom_errorbar(data = df_summary, aes(x=freq_cat, ymin=lower, ymax=upper, color = model), width=0.1, alpha=0.8) +
    geom_hline(yintercept=0.5, color="blue", alpha=0.5) +
    facet_grid(~test) +
    coord_cartesian(ylim=c(0,1)) +
    scale_color_brewer(palette = "Dark2") +
    scale_x_continuous(labels=c(3, 10, 30, 100), breaks=c(0.5, 1, 1.5, 2), minor_breaks = NULL) +
    ylab("Accuracy") +
    xlab("# Exposures in Training Data (log scale)") +
    ggtitle(title) +
    theme(strip.text=element_text(size = 12),
          axis.text=element_text(size=14),
          legend.text=element_text(size=12),
          legend.title=element_text(size=14),
          axis.title=element_text(size=14),
          legend.position = "bottom", 
          panel.grid.minor = element_blank())
#ggsave(filename,height=h,width=w)

}

```

```{r}
plot_vars = function(df_raw, filename, h, w, title){
  
ggplot() +
    theme_bw()+
    stat_smooth(geom = "line", data = df_raw, aes(x=log10(freq_cat), y=acc), color="blue", method = 'glm', method.args = list(family = "binomial"), size = 1, alpha=0.5) +
    stat_smooth(data = df_raw, aes(x=log10(freq_cat), y=acc), color="blue", method = 'glm', method.args = list(family = "binomial"), size = 0, alpha=0.2) +
    
    stat_smooth(geom = "line", data = df_raw, aes(x=log10(freq_cat), y=acc, color=syn_cat), method = 'glm', method.args = list(family = "binomial"), size = 1, alpha=0.5) +
    stat_smooth(data = df_raw, aes(x=log10(freq_cat), y=acc, color=syn_cat), method = 'glm', method.args = list(family = "binomial"), size = 0, alpha=0.2) +
    geom_hline(yintercept=0.5, color="blue", alpha=0.5) +
    facet_grid(model~test) +
    coord_cartesian(ylim=c(0,1)) +
    scale_x_continuous(labels=c(3, 10, 30, 100), breaks=c(0.5, 1, 1.5, 2), minor_breaks = NULL) +
    ylab("Accuracy") +
    xlab("# Exposures in Training Data (log scale)") +
    ggtitle(title) +
    theme(strip.text=element_text(size = 12),
          axis.text=element_text(size=12),
          legend.text=element_text(size=12),
          legend.title=element_text(size=12),
          axis.title=element_text(size=12),
          legend.position = "bottom", 
          panel.grid.minor = element_blank())
#ggsave(filename,height=h,width=w)
    
}

```



### Read in the data
```{r}

d_agg = read.csv("argstruct_data.csv") %>%
  mutate(vb_freq = as.factor(vb_freq),
         vbd_freq = as.factor(vbd_freq),
         total_freq = as.factor(total_freq)) %>%
  mutate(model = factor(model, levels = c("5gram", "lstm", "actionLstm", "rnng"))) %>%
  mutate(acc = if_else(obj_exp > 0, 1, 0),
         acc = if_else(is_trans == "Intrans", 1-acc, acc)) %>%
  mutate(acc = if_else(obj_exp == 0, 0, acc)) %>%
  filter(is_trans != "Ambitrans")%>%
  mutate(syn_cat = is_trans) %>%
  mutate(model=as.character(model),
        model = if_else(model == "5gram", "ngram", model))



```


#### Base-Present
```{r}
d_arg_base_pres = d_agg %>%
  filter(test == "base-pres" & is_trans != "Ambitrans") %>%
  mutate(freq_cat = vb_freq) %>%
  mutate(freq_cat = as.numeric(as.character(freq_cat))) %>%
  mutate(test = "Active, Infinitival")

d_arg_base_past = d_agg %>%
  filter(test == "base-nomod" & is_trans != "Ambitrans") %>%
  mutate(freq_cat = vbd_freq) %>%
  mutate(freq_cat = as.numeric(as.character(freq_cat))) %>% 
  mutate(test = "Active, Past Tense")

d_arg_base = rbind(d_arg_base_pres, d_arg_base_past) %>%
  mutate(test = factor(test, levels = c("Active, Infinitival", "Active, Past Tense")))

d_arg_base_summary = d_arg_base %>% 
  mutate(freq_cat = log10(freq_cat)) %>%
  group_by(model, freq_cat, test) %>%
     summarise(m = mean(acc),
              upper = binconf(sum(acc), n())[2],
              lower = binconf(sum(acc), n())[3])%>%
  ungroup()

#plot_vars(d_arg_base, "./images/vars/v_arg_base.pdf", 5, 6, "Argument Structure: Active Contexts")
#plot_accs(d_arg_base, d_arg_base_summary, "./images/arg_base.pdf", 5, 6, "Argument Structure: Active Contexts")


```

### Impact of Passive Voice on Transitive Verb
```{r}
lm = d_arg_base_past %>%
  filter(model == "actionLstm") %>%
  # sentence_id = X
  glm(acc ~ percent_VBN + (1|X), family="binomial", data = .)
summary(lm)

lm = d_arg_base_past %>%
  filter(model == "rnng") %>%
  # sentence_id = X
  glm(acc ~ percent_VBN + (1|X), family="binomial", data = .)
summary(lm)


lm = d_arg_base_past %>%
  filter(model == "lstm") %>%
  # sentence_id = X
  glm(acc ~ percent_VBN + (1|X), family="binomial", data = .)
summary(lm)


cor.test(d_arg_base_past$percent_VBN, d_arg_base_past$total)

```



Statistics
```{r}
# Fewshot Learning
d_arg_base_pres %>%
  group_by(test, freq_cat) %>% do({fewshot_test(.)}) %>% ungroup() %>%
arrange(test) %>%
gather(model, p, c(t.ngram, t.lstm, t.action, t.rnng)) %>% group_by(test, model) %>% filter(p<0.05) %>% summarise(n = n())

d_arg_base_pres %>%
  group_by(test, model) %>% do({exposure_test(.)}) %>% ungroup()

# Structural supervision
d_arg_base_pres %>%
  group_by(test) %>% do({ supervision_test(.)}) %>% ungroup() %>%
arrange(test)
 
```

### Statistics
```{r}
# Fewshot Learning
d_arg_base_past %>%
  group_by(test, freq_cat) %>% do({fewshot_test(.)}) %>% ungroup() %>%
arrange(test, freq_cat) %>%
gather(model, p, c(t.ngram, t.lstm, t.action, t.rnng)) %>% group_by(test, model) %>% filter(p<0.05) %>% summarise(n = n())

d_arg_base_past %>%
  group_by(test, model) %>% do({exposure_test(.)}) %>% ungroup()

# Structural supervision
d_arg_base_past %>%
  group_by(test) %>% do({ supervision_test(.)}) %>% ungroup() %>%
arrange(test)
 
```


## Passive Context Few Shot Learning


```{r, Expectation}

d_arg_transf = d_agg %>%
  filter( test=="transf-nomod" | test == "transf-mod" | test == "transf-longmod") %>%
  mutate(freq_cat = vbd_freq) %>%
  mutate(freq_cat = as.numeric(as.character(freq_cat))+1 ) %>%
  mutate(test = case_when(
    test == "transf-nomod" ~ "Passive no Mod.",
    test =="transf-mod" ~ "Passive w/ Short Mod.",
    test == "transf-longmod" ~ "Passive w/ Long Mod."
  ), test = factor(test, levels = c("Passive no Mod.", "Passive w/ Short Mod.", "Passive w/ Long Mod.")))

d_arg_transf_summary = d_arg_transf %>%
  mutate(freq_cat = log10(freq_cat)) %>%
  group_by(model, freq_cat, test) %>%
    summarise(m = mean(acc),
              upper = binconf(sum(acc), n())[2],
              lower = binconf(sum(acc), n())[3])%>%
  ungroup()

#plot_vars(d_arg_transf, "./images/vars/v_arg_transf.pdf", 5, 6, "Argument Structure: Transformed Contexts")
#plot_accs(d_arg_transf, d_arg_transf_summary, "./images/arg_transf.pdf", 5, 6, "Argument Structure: Transformed Contexts")

```

### Statistics
```{r}

# Fewshot Learning
d_arg_transf %>%
  group_by(test, freq_cat) %>% do({fewshot_test(.)}) %>% ungroup() %>%
arrange(test, freq_cat)%>%
gather(model, p, c(t.ngram, t.lstm, t.action, t.rnng)) %>% group_by(test, model) %>% filter(p<0.05) %>% summarise(n = n())

d_arg_transf %>%
  group_by(test, model) %>% do({exposure_test(.)}) %>% ungroup()

# Structural supervision
d_arg_transf %>%
  group_by(test) %>% do({ supervision_test(.)}) %>% ungroup() %>%
arrange(test)
 
 
```

## Transformation & Invarience

```{r}
d_agg = read.csv("./arg_transf.csv") %>%
  mutate(acc = if_else(obj_exp > 0, 1, 0)) %>%
  mutate(acc = if_else(is_trans == "Intrans", 1-acc, acc)) %>%
  mutate(acc = if_else(obj_exp == 0, 0, acc)) %>%
  filter(is_trans != "Ambitrans")%>%
  mutate(syn_cat = is_trans) %>%
  mutate(model=as.character(model),
        model = if_else(model == "5gram", "ngram", model)) %>%
   mutate(test = case_when(
    test == "transf-nomod" ~ "Passive no Mod.",
    test =="transf-mod" ~ "Passive w/ Short Mod.",
    test == "transf-longmod" ~ "Passive w/ Long Mod."
  ), test = factor(test, levels = c("Passive no Mod.", "Passive w/ Short Mod.", "Passive w/ Long Mod.")))

arg_transf_invar = d_agg %>%
  mutate(freq_cat = as.factor(vbd_freq)) %>%
  mutate(freq_cat = as.numeric(as.character(freq_cat)))

arg_transf_invar_summary =  arg_transf_invar%>%
  mutate(freq_cat = log10(freq_cat)) %>%
  group_by(model, freq_cat, test) %>%
     summarise(m = mean(acc),
              upper = binconf(sum(acc), n())[2],
              lower = binconf(sum(acc), n())[3])%>%
  ungroup()

#plot_vars(arg_transf_invar, "./images/vars/arg_transf_invar.pdf", 5, 6, "Argument Structure: Invariance")
#plot_accs(arg_transf_invar, arg_transf_invar_summary, "./images/arg_transf_invar.pdf", 5, 6, "Argument Structure: Invariance")

```

### Statistics
```{r}
# Fewshot Learning
arg_transf_invar %>%
  group_by(test, freq_cat) %>% do({fewshot_test(.)}) %>% ungroup() %>%
arrange(test, freq_cat)%>%
gather(model, p, c(t.ngram, t.lstm, t.action, t.rnng)) %>% group_by(test, model) %>% filter(p<0.05) %>% summarise(n = n())

arg_transf_invar %>%
  group_by(test, model) %>% do({exposure_test(.)}) %>% ungroup()

# Structural supervision
arg_transf_invar %>%
  group_by(test) %>% do({ supervision_test(.)}) %>% ungroup() %>%
arrange(test)
 
 
 
```

# Nominal Number Learning

Read in the data. 

```{r}

d_agg = read.csv("number_data.csv") %>%
  mutate(freq_cat = as.character(freq_cat),
          freq_cat = if_else((freq>10 & freq<=20), "20", freq_cat),
         freq_cat = if_else((freq>20 & freq <= 50), "50", freq_cat),
         freq_cat = if_else((freq>50 & freq < 100), "100", freq_cat)) %>%
  mutate(freq_cat = as.factor(freq_cat)) %>%
  mutate(model = factor(model, levels = c("5gram", "lstm", "actionLstm", "rnng"))) %>%
  mutate(test = factor(test, levels = c("base_simple", "base_pp", "base_rc", "transf_simple", "transf_mod"))) %>%
  mutate(acc = if_else(pl_exp > 0, 1, 0)) %>%
  mutate(acc = if_else(pos == "NN", 1-acc, acc)) %>%
  mutate(acc = if_else(pl_exp == 0, 0, acc)) %>%
  mutate(freq_cat = as.numeric(as.character(freq_cat)))%>%
  mutate(syn_cat = pos)%>%
  mutate(model=as.character(model),
        model = if_else(model == "5gram", "ngram", model))



```



## Base Context Few Shot Learning

```{r}
d_num_base_acc = d_agg %>%
  drop_na() %>%
  filter(test == "base_pp" | test == "base_simple" | test == "base_rc") %>%
  mutate(test = case_when(
    test == "base_simple" ~ "No Modifier",
    test =="base_pp" ~ "PP Modifier",
    test == "base_rc" ~ "RC Modifier"
  ), test = factor(test, levels = c("No Modifier", "PP Modifier", "RC Modifier")))

d_num_base_acc %>%
  group_by(model, test, freq_cat, syn_cat) %>%
  summarise(n=n() / 20)

d_num_base_acc_summary = d_num_base_acc %>%
  mutate(freq_cat = log10(freq_cat)) %>%
  group_by(model, freq_cat, test) %>%
    summarise(m = mean(acc),
              upper = binconf(sum(acc), n())[2],
              lower = binconf(sum(acc), n())[3])%>%
  ungroup()

#plot_vars(d_num_base_acc, "./images/vars/v_number-base.pdf", 5, 6, "Nominal Number: Base Contexts")
#plot_accs(d_num_base_acc, d_num_base_acc_summary, "./images/number-base.pdf", 5, 6, "Nominal Number: Base Contexts")
#plot_accs_byverb(d_num_base_acc, "./images/number-base-byverb.pdf", 5, 6, "Nominal Number: Base Contexts")

```

```{r}
d_num_base_acc %>%
  mutate(freq_cat = log10(freq_cat)) %>%
  group_by(model, freq_cat, test, verb, pos) %>%
    summarise(m = mean(acc),
              upper = binconf(sum(acc), n())[2],
              lower = binconf(sum(acc), n())[3])%>%
  ungroup() %>%
  mutate(verb = as.character(verb)) %>%
  
  ggplot(aes(x=freq_cat, y=m, label=verb, color = pos)) +
    theme_bw()+
    geom_text(size=2, position=position_jitter(width=0.1,height=0.1)) +
    geom_hline(yintercept=0.5, color="blue", alpha=0.5) +
    facet_grid(model~test) +
    coord_cartesian(ylim=c(0,1)) +
    #scale_color_brewer(palette = "Dark2") +
    scale_x_continuous(labels=c(3, 10, 30, 100), breaks=c(0.5, 1, 1.5, 2), minor_breaks = NULL) +
    ylab("Accuracy") +
    xlab("# Exposures in Training Data (log scale)") +
    theme(strip.text=element_text(size = 12),
          axis.text=element_text(size=14),
          legend.text=element_text(size=12),
          legend.title=element_text(size=14),
          axis.title=element_text(size=14),
          legend.position = "none", 
          panel.grid.minor = element_blank())
#ggsave("./images/by-verb.png",height=12,width=20)


```


### Statistics
```{r}
# Exposure learning
d_num_base_acc %>%
  group_by(test, freq_cat) %>% do({fewshot_test(.)}) %>% ungroup() %>%
arrange(test, freq_cat) %>%
gather(model, p, c(t.ngram, t.lstm, t.action, t.rnng)) %>% group_by(test, model) %>% filter(p<0.05) %>% summarise(n = n())

d_num_base_acc %>%
  group_by(test, model) %>% do({exposure_test(.)}) %>% ungroup()

# Structural supervision
d_num_base_acc %>%
  group_by(test) %>% do({ supervision_test(.)}) %>% ungroup() %>%
arrange(test)

```



## Transformed Context Few Shot Learning

```{r}
intersection = c('threat', 'broker', 'deductibility', 'nameplates', 'businessman', 'listing', 'lobbyist', 'someone', 'desk', 'details', 'lawyer', 'dispute', 'forces', 'hearings', 'creators')

d_num_transf_acc = d_agg %>%
  filter(!(verb %in% intersection)) %>%
  filter(test == "transf_simple" | test == "transf_mod") %>%
  mutate(test = case_when(
    test == "transf_simple" ~ "Polar Question",
    test =="transf_mod" ~ "Polar Question w/ Modifier"
  ), test = factor(test, levels = c("Polar Question", "Polar Question w/ Modifier")))
  
d_num_transf_acc_summary = d_num_transf_acc %>%
  mutate(freq_cat = log10(freq_cat)) %>%
  group_by(model, freq_cat, test) %>%
     summarise(m = mean(acc),
              upper = binconf(sum(acc), n())[2],
              lower = binconf(sum(acc), n())[3])%>%
  ungroup()

#plot_vars(d_num_transf_acc, "./images/vars/v_number-transf.pdf", 5, 6, "Nominal Number: Transformed Contexts")
#plot_accs(d_num_transf_acc, d_num_transf_acc_summary, "./images/number-transf.pdf", 5, 6, "Nominal Number: Transformed Contexts")


```


### Statistics
```{r}

# Few-shot Learning
d_num_transf_acc %>%
  group_by(test, freq_cat) %>% do({fewshot_test(.)}) %>% ungroup() %>%
arrange(test, freq_cat) %>%
gather(model, p, c(t.ngram, t.lstm, t.action, t.rnng)) %>% group_by(test, model) %>% filter(p<0.05) %>% summarise(n = n())

d_num_transf_acc %>%
  group_by(test, model) %>% do({exposure_test(.)}) %>% ungroup()
  
# Structural supervision
d_num_transf_acc %>%
  group_by(test) %>% do({ supervision_test(.)}) %>% ungroup() %>%
arrange(test)

 
```

